# Generated by Django 5.1.2 on 2024-11-12 05:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import intranetapp.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100, unique=True)),
                ('dept_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('desig_id', models.AutoField(primary_key=True, serialize=False)),
                ('desig_name', models.CharField(max_length=100, unique=True)),
                ('desig_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Entity_Type',
            fields=[
                ('entity_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=100, unique=True)),
                ('entity_guide', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('gender_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender_name', models.CharField(max_length=12, unique=True)),
                ('gender_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('title_id', models.AutoField(primary_key=True, serialize=False)),
                ('title_name', models.CharField(max_length=12, unique=True)),
                ('title_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('cluster_id', models.AutoField(primary_key=True, serialize=False)),
                ('cluster_name', models.CharField(blank=True, max_length=200, null=True)),
                ('institute', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=12)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranetapp.dept')),
            ],
        ),
        migrations.CreateModel(
            name='Roles_Permission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.entity_type')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission_id', models.ManyToManyField(blank=True, null=True, to='intranetapp.roles_permission')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('start_year', models.CharField(max_length=100)),
                ('end_year', models.CharField(max_length=100)),
                ('start_month', models.CharField(max_length=30)),
                ('end_month', models.CharField(max_length=30)),
                ('session_code', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'unique_together': {('start_year', 'end_year', 'start_month', 'end_month')},
            },
        ),
        migrations.CreateModel(
            name='EntityRegistration',
            fields=[
                ('reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('registeration_code', models.CharField(blank=True, max_length=200, null=True)),
                ('registeration_name', models.CharField(blank=True, max_length=200, null=True)),
                ('faculty_advisory_name', models.CharField(blank=True, max_length=200, null=True)),
                ('faculty_advisory_email', models.CharField(max_length=100)),
                ('faculty_advisory_empcode', models.CharField(blank=True, max_length=20, null=True)),
                ('faculty_advisory_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter your mobile number', max_length=128, null=True, region=None)),
                ('faculty_co_advisory_name', models.CharField(blank=True, max_length=200, null=True)),
                ('faculty_co_advisory_email', models.CharField(max_length=100)),
                ('faculty_co_advisory_empcode', models.CharField(blank=True, max_length=20, null=True)),
                ('faculty_co_advisory_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter your mobile number', max_length=128, null=True, region=None)),
                ('Secretary_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Secretary_email', models.CharField(blank=True, max_length=100, null=True)),
                ('Secretary_uid', models.CharField(blank=True, max_length=20, null=True)),
                ('Secretary_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter your mobile number', max_length=128, null=True, region=None)),
                ('Joint_Secretary_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Joint_Secretary_email', models.CharField(blank=True, max_length=100, null=True)),
                ('Joint_Secretary_uid', models.CharField(blank=True, max_length=20, null=True)),
                ('Joint_Secretary_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter your mobile number', max_length=128, null=True, region=None)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.dept')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranetapp.entity_type')),
                ('session_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.session')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='intranetapp.session')),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter your mobile number', max_length=128, null=True, region=None, unique=True)),
                ('password', models.TextField(default=intranetapp.models.generate_random_password)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=12)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='Last login IP address', null=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranetapp.dept')),
                ('desig_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.designation')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranetapp.gender')),
                ('groups', models.ManyToManyField(blank=True, related_name='user_table_groups', to='auth.group', verbose_name='groups')),
                ('title_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.title')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_table_permissions', to='auth.permission', verbose_name='user permissions')),
                ('user_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.roles')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_email', models.EmailField(max_length=254)),
                ('receiver_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranetapp.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='EntrityRequest',
            fields=[
                ('entcr_id', models.AutoField(primary_key=True, serialize=False)),
                ('proposed_name', models.CharField(max_length=100)),
                ('proposed_date', models.DateField()),
                ('proposed_by', models.CharField(max_length=100)),
                ('proposer_name', models.CharField(max_length=100)),
                ('emp_code', models.CharField(blank=True, max_length=20, null=True)),
                ('proposer_email', models.EmailField(max_length=254)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter your mobile number', max_length=128, null=True, region=None)),
                ('entity_nature', models.CharField(max_length=100)),
                ('student_sec_1_name', models.CharField(max_length=100)),
                ('student_sec_1_email', models.CharField(max_length=100)),
                ('student_sec_1_uid', models.CharField(blank=True, max_length=20, null=True)),
                ('student_sec_1_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter your mobile number', max_length=128, null=True, region=None)),
                ('student_sec_2_name', models.CharField(max_length=100)),
                ('student_sec_2_email', models.CharField(max_length=100)),
                ('student_sec_2_uid', models.CharField(blank=True, max_length=20, null=True)),
                ('student_sec_2_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter your mobile number', max_length=128, null=True, region=None)),
                ('student_advsec_1_name', models.CharField(max_length=100)),
                ('student_advsec_1_email', models.CharField(max_length=100)),
                ('student_advsec_1_uid', models.CharField(blank=True, max_length=20, null=True)),
                ('student_advsec_1_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter your mobile number', max_length=128, null=True, region=None)),
                ('student_advsec_2_name', models.CharField(max_length=100)),
                ('student_advsec_2_email', models.CharField(max_length=100)),
                ('student_advsec_2_uid', models.CharField(blank=True, max_length=20, null=True)),
                ('student_advsec_2_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter your mobile number', max_length=128, null=True, region=None)),
                ('faculty_adv_1_name', models.CharField(max_length=100)),
                ('faculty_adv_1_email', models.CharField(max_length=100)),
                ('faculty_adv_1_empcode', models.CharField(blank=True, max_length=20, null=True)),
                ('faculty_adv_1_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter your mobile number', max_length=128, null=True, region=None)),
                ('faculty_adv_2_name', models.CharField(max_length=100)),
                ('faculty_adv_2_email', models.CharField(max_length=100)),
                ('faculty_adv_2_empcode', models.CharField(blank=True, max_length=20, null=True)),
                ('faculty_adv_2_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter your mobile number', max_length=128, null=True, region=None)),
                ('faculty_coadv_1_name', models.CharField(max_length=100)),
                ('faculty_coadv_1_email', models.CharField(max_length=100)),
                ('faculty_coadv_1_empcode', models.CharField(blank=True, max_length=20, null=True)),
                ('faculty_coadv_1_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter your mobile number', max_length=128, null=True, region=None)),
                ('faculty_coadv_2_name', models.CharField(max_length=100)),
                ('faculty_coadv_2_email', models.CharField(max_length=100)),
                ('faculty_coadv_2_empcode', models.CharField(blank=True, max_length=20, null=True)),
                ('faculty_coadv_2_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter your mobile number', max_length=128, null=True, region=None)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'approved'), ('Interview Scheduled', 'interview Scheduled'), ('Rejected', 'Rejected'), ('Request Hold', 'Request Hold')], default='Pending', max_length=100)),
                ('referal', models.TextField(blank=True, null=True)),
                ('email_body', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranetapp.dept')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranetapp.entity_type')),
                ('session_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.session')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('emp_code', 'session_code'), name='unique_empcode_in_session'), models.UniqueConstraint(fields=('proposer_email', 'session_code'), name='unique_proposer_email_in_session')],
            },
        ),
    ]
