# Generated by Django 5.1.2 on 2024-11-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_table',
            old_name='department',
            new_name='dept_id',
        ),
    ]
