# Generated by Django 5.1.2 on 2024-11-21 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0002_rename_department_user_table_dept_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipRegistration',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(blank=True, max_length=200, null=True)),
                ('member_uid', models.CharField(blank=True, max_length=20, null=True)),
                ('member_email', models.EmailField(max_length=254)),
                ('membership_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranetapp.dept')),
                ('entity_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.entity_type')),
                ('reg_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.entityregistration')),
                ('session_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.session')),
            ],
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to='intranetapp.membershipregistration')),
            ],
        ),
    ]
