# Generated by Django 5.1.2 on 2024-11-21 10:44

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0003_membershipregistration_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipregistration',
            name='member_mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter your mobile number', max_length=128, null=True, region=None),
        ),
    ]
