# Generated by Django 5.1.2 on 2024-11-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0004_membershipregistration_member_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipregistration',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=12),
        ),
    ]
