# Generated by Django 5.1.2 on 2024-11-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0005_alter_membershipregistration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityregistration',
            name='faculty_co_advisory_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
