# Generated by Django 5.1.2 on 2024-11-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0006_alter_entityregistration_faculty_co_advisory_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity_type',
            name='entity_short',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
