# Generated by Django 5.1.2 on 2024-12-05 10:07

import django.db.models.deletion
import intranetapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0007_entity_type_entity_short'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='entity_media/banners/', validators=[intranetapp.models.validate_image_file_extension])),
                ('logo', models.ImageField(blank=True, null=True, upload_to='entity_media/logos/', validators=[intranetapp.models.validate_image_file_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='intranetapp.entityregistration')),
            ],
        ),
    ]
