# Generated by Django 5.1.2 on 2024-12-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0008_entitymedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitymedia',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'approved')], default='Pending', max_length=100),
        ),
    ]
