# Generated by Django 5.1.2 on 2024-12-14 05:09

import intranetapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0009_entitymedia_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitymedia',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='entity_media/banners/temp/', validators=[intranetapp.models.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='entitymedia',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='entity_media/logos/temp/', validators=[intranetapp.models.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='entitymedia',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=100),
        ),
    ]
