# Generated by Django 5.1.2 on 2024-12-14 05:29

import intranetapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0010_alter_entitymedia_banner_alter_entitymedia_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitymedia',
            name='temp_banner',
            field=models.ImageField(blank=True, null=True, upload_to='entity_media/banners/temp/', validators=[intranetapp.models.validate_image_file_extension]),
        ),
        migrations.AddField(
            model_name='entitymedia',
            name='temp_logo',
            field=models.ImageField(blank=True, null=True, upload_to='entity_media/logos/temp/', validators=[intranetapp.models.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='entitymedia',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='entity_media/banners/'),
        ),
        migrations.AlterField(
            model_name='entitymedia',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='entity_media/logos/'),
        ),
    ]
