# Generated by Django 5.1.2 on 2024-12-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0011_entitymedia_temp_banner_entitymedia_temp_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitymedia',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='entity_media/banners/perm/'),
        ),
        migrations.AlterField(
            model_name='entitymedia',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='entity_media/logos/perm/'),
        ),
    ]
