# Generated by Django 5.1.2 on 2024-12-24 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0012_alter_entitymedia_banner_alter_entitymedia_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity_Activity',
            fields=[
                ('act_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='EventJoinee',
            fields=[
                ('ej_id', models.AutoField(primary_key=True, serialize=False)),
                ('membership_code', models.CharField(blank=True, max_length=100, null=True)),
                ('qr_code', models.CharField(blank=True, help_text='Unique code generated for QR verification', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('er_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Approved', 'Approved')], default='Pending', max_length=100)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('limit', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='events_published/poster/')),
                ('duration', models.FloatField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('High', 'High')], default='Low', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventsUploads',
            fields=[
                ('uploads_id', models.AutoField(primary_key=True, serialize=False)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='events_uploads/pdfs/')),
                ('event_name', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Approved', 'Approved')], default='Pending', max_length=100)),
                ('remark', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='entityregistration',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entityregistration',
            name='eligibilty',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entityregistration',
            name='fee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='membershipregistration',
            constraint=models.UniqueConstraint(fields=('member_uid', 'entity_id', 'session_code'), name='unique_uid_entity_session'),
        ),
        migrations.AddField(
            model_name='entity_activity',
            name='entity_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.entity_type'),
        ),
        migrations.AddField(
            model_name='entityregistration',
            name='act_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.entity_activity'),
        ),
        migrations.AddField(
            model_name='eventjoinee',
            name='reg_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.entityregistration'),
        ),
        migrations.AddField(
            model_name='eventjoinee',
            name='session_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.session'),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='act_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.entity_activity'),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='reg_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.entityregistration'),
        ),
        migrations.AddField(
            model_name='eventjoinee',
            name='er_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='intranetapp.eventrequest'),
        ),
        migrations.AddField(
            model_name='eventsuploads',
            name='reg_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.entityregistration'),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='uploads_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranetapp.eventsuploads', unique=True),
        ),
    ]
