# Generated by Django 5.1.2 on 2024-12-26 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0013_entity_activity_eventjoinee_eventrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventjoinee',
            name='er_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranetapp.eventrequest'),
        ),
    ]
