# Generated by Django 5.1.2 on 2024-12-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0014_alter_eventjoinee_er_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventjoinee',
            name='reg_id',
        ),
    ]
