# Generated by Django 5.1.2 on 2024-12-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0015_remove_eventjoinee_reg_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventjoinee',
            old_name='membership_code',
            new_name='member_uid',
        ),
    ]
