# Generated by Django 5.1.2 on 2024-12-27 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0016_rename_membership_code_eventjoinee_member_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(auto_now_add=True)),
                ('is_present', models.BooleanField(default=False)),
                ('is_entry', models.BooleanField(default=False)),
                ('is_exit', models.BooleanField(default=False)),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.CharField(blank=True, help_text='QR code for attendance verification', max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('er_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranetapp.eventrequest')),
                ('event_joinee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='intranetapp.eventjoinee')),
            ],
            options={
                'unique_together': {('event_joinee', 'attendance_date')},
            },
        ),
    ]
