# Generated by Django 5.1.2 on 2024-12-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0017_eventattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendance',
            name='member_uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
