# Generated by Django 5.1.2 on 2025-01-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0018_eventattendance_member_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendance',
            name='entry_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventattendance',
            name='exit_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
