# Generated by Django 5.1.2 on 2025-01-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0019_alter_eventattendance_entry_time_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membershipregistration',
            name='unique_uid_entity_session',
        ),
        migrations.AddConstraint(
            model_name='membershipregistration',
            constraint=models.UniqueConstraint(fields=('member_uid', 'reg_id', 'session_code'), name='unique_uid_entity_session'),
        ),
    ]
