# Generated by Django 5.1.2 on 2025-01-06 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0020_remove_membershipregistration_unique_uid_entity_session_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membershipregistration',
            name='unique_uid_entity_session',
        ),
    ]
