# Generated by Django 5.1.2 on 2025-01-07 05:00

import intranetapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0021_remove_membershipregistration_unique_uid_entity_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginlog',
            name='token_expiration_time',
            field=models.DateTimeField(default=intranetapp.models.default_expiration_time),
        ),
    ]
