# Generated by Django 5.1.2 on 2025-01-07 07:03

import intranetapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0022_userloginlog_token_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='created_at',
            field=models.DateTimeField(default=intranetapp.models.default_ist_time),
        ),
        migrations.AlterField(
            model_name='userloginlog',
            name='login_time',
            field=models.DateTimeField(default=intranetapp.models.default_ist_time),
        ),
    ]
