# Generated by Django 5.1.2 on 2025-01-07 07:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0023_alter_user_table_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginlog',
            name='login_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
