# Generated by Django 5.1.2 on 2025-01-11 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0024_alter_userloginlog_login_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityregistration',
            name='session_code',
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='session_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.session'),
        ),
        migrations.AddField(
            model_name='eventsuploads',
            name='session_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.session'),
        ),
        migrations.AddField(
            model_name='user_table',
            name='session_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.session'),
        ),
    ]
