# Generated by Django 5.1.2 on 2025-01-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0025_remove_entityregistration_session_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsuploads',
            name='session_code',
        ),
    ]
