# Generated by Django 5.1.2 on 2025-01-11 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0026_remove_eventsuploads_session_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventjoinee',
            name='session_code',
        ),
        migrations.RemoveField(
            model_name='eventrequest',
            name='session_code',
        ),
        migrations.RemoveField(
            model_name='membershipregistration',
            name='session_code',
        ),
        migrations.RemoveField(
            model_name='user_table',
            name='session_code',
        ),
    ]
