# Generated by Django 5.1.2 on 2025-01-11 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0027_remove_eventjoinee_session_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventjoinee',
            name='session_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.currentsession'),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='session_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.currentsession'),
        ),
        migrations.AddField(
            model_name='membershipregistration',
            name='session_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.currentsession'),
        ),
        migrations.AddField(
            model_name='user_table',
            name='session_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.currentsession'),
        ),
    ]
