# Generated by Django 5.1.2 on 2025-01-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0028_eventjoinee_session_code_eventrequest_session_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='is_cordinator',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=12),
        ),
    ]
