# Generated by Django 5.1.2 on 2025-01-21 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0029_user_table_is_cordinator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('bud_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_budget', models.IntegerField(blank=True, null=True)),
                ('total_proposed', models.IntegerField(blank=True, null=True)),
                ('actual_budget', models.IntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranetapp.dept')),
                ('session_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.currentsession')),
            ],
        ),
    ]
