# Generated by Django 5.1.2 on 2025-01-21 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0030_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='proposedcalender',
            fields=[
                ('pc_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('Flagship', 'Flagship'), ('Monthly', 'Monthly'), ('Regular', 'Regular')], default='Low', max_length=100)),
                ('event_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('proposed_budget', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Approved', 'Approved')], default='Pending', max_length=100)),
                ('description', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('act_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.entity_activity')),
                ('reg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranetapp.entityregistration')),
                ('session_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.currentsession')),
            ],
        ),
    ]
