# Generated by Django 5.1.2 on 2025-01-22 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0031_proposedcalender'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposedcalender',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.dept'),
        ),
    ]
