# Generated by Django 5.1.2 on 2025-01-27 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0032_proposedcalender_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrequest',
            name='uploads_id',
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='budget',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='collected_by',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='collected_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='end_date_propsed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='end_time_proposed',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='organiser_guest_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='received_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='start_date_propsed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='start_time_proposed',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.user_table'),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='event_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='limit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
