# Generated by Django 5.1.2 on 2025-01-27 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0033_remove_eventrequest_uploads_id_eventrequest_budget_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventrequest',
            old_name='end_date_propsed',
            new_name='end_date_proposed',
        ),
        migrations.RenameField(
            model_name='eventrequest',
            old_name='start_date_propsed',
            new_name='start_date_proposed',
        ),
    ]
