# Generated by Django 5.1.2 on 2025-01-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0034_rename_end_date_propsed_eventrequest_end_date_proposed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequest',
            name='activity_type',
            field=models.CharField(choices=[('Flagship', 'Flagship'), ('Monthly', 'Monthly'), ('Regular', 'Regular')], default='Regular', max_length=100),
        ),
    ]
