# Generated by Django 5.1.2 on 2025-01-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0035_eventrequest_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequest',
            name='file_status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Processing With DAA', 'Processing With DAA'), ('Pending With PVC', 'Pending With PVC'), ('Return To Department', 'Return To Department')], default='In Progress', max_length=100),
        ),
    ]
