# Generated by Django 5.1.2 on 2025-02-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0036_eventrequest_file_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrequest',
            name='file_status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Processing With DAA', 'Processing With DAA'), ('Pending With PVC', 'Pending With PVC'), ('Submitted To Department', 'Submitted To Department')], default='In Progress', max_length=100),
        ),
    ]
