# Generated by Django 5.1.2 on 2025-02-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0037_alter_eventrequest_file_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrityrequest',
            name='faculty_adv_2_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entrityrequest',
            name='faculty_adv_2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entrityrequest',
            name='faculty_coadv_2_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entrityrequest',
            name='faculty_coadv_2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entrityrequest',
            name='student_advsec_2_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entrityrequest',
            name='student_advsec_2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entrityrequest',
            name='student_sec_2_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entrityrequest',
            name='student_sec_2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
