# Generated by Django 5.1.3 on 2025-03-06 07:04

import django.db.models.deletion
import intranetapp.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0038_alter_entrityrequest_faculty_adv_2_email_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entrityrequest',
            name='unique_empcode_in_session',
        ),
        migrations.AddField(
            model_name='entitymedia',
            name='co_advisor_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='entity_media/co_advisor/perm/'),
        ),
        migrations.AddField(
            model_name='entitymedia',
            name='faculty_advisory_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='entity_media/faculty_advisory/perm/'),
        ),
        migrations.AddField(
            model_name='entitymedia',
            name='join_secretary_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='entity_media/join_secretary/perm/'),
        ),
        migrations.AddField(
            model_name='entitymedia',
            name='secretary_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='entity_media/secretary/perm/'),
        ),
        migrations.AddField(
            model_name='entitymedia',
            name='temp_co_advisor_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='entity_media/co_advisor/temp/', validators=[intranetapp.models.validate_image_file_extension]),
        ),
        migrations.AddField(
            model_name='entitymedia',
            name='temp_faculty_advisory_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='entity_media/faculty_advisory/temp/', validators=[intranetapp.models.validate_image_file_extension]),
        ),
        migrations.AddField(
            model_name='entitymedia',
            name='temp_join_secretary_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='entity_media/join_secretary/temp/', validators=[intranetapp.models.validate_image_file_extension]),
        ),
        migrations.AddField(
            model_name='entitymedia',
            name='temp_secretary_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='entity_media/secretary/temp/', validators=[intranetapp.models.validate_image_file_extension]),
        ),
        migrations.AddField(
            model_name='entityregistration',
            name='categories',
            field=models.TextField(blank=True, default='Debate,Public Speaking,Writing and Editing,Leadership,Creative Expression', null=True),
        ),
        migrations.AlterField(
            model_name='entityregistration',
            name='about',
            field=models.TextField(blank=True, default='A student society, student association, university society, student club, university club, or student organization is a society or an organization, operated by students at a university, college, or other educational institution, whose membership typically consists only of students', null=True),
        ),
        migrations.AlterField(
            model_name='entityregistration',
            name='eligibilty',
            field=models.TextField(blank=True, default='Anyone can join a club or participate in extracurricular activities.', null=True),
        ),
        migrations.AlterField(
            model_name='entrityrequest',
            name='emp_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='entrityrequest',
            name='faculty_adv_1_empcode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='entrityrequest',
            name='faculty_adv_1_mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Enter your mobile number', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='entrityrequest',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Enter your mobile number', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='entrityrequest',
            name='session_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranetapp.session'),
        ),
        migrations.AlterField(
            model_name='entrityrequest',
            name='student_advsec_1_uid',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='entrityrequest',
            name='student_sec_1_mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Enter your mobile number', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='entrityrequest',
            name='student_sec_1_uid',
            field=models.CharField(max_length=20),
        ),
    ]
