# Generated by Django 5.1.3 on 2025-03-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0039_remove_entrityrequest_unique_empcode_in_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityregistration',
            name='about',
            field=models.TextField(default='A student society, student association, university society, student club, university club, or student organization is a society or an organization, operated by students at a university, college, or other educational institution, whose membership typically consists only of students'),
        ),
        migrations.AlterField(
            model_name='entityregistration',
            name='categories',
            field=models.TextField(default='Debate,Public Speaking,Writing and Editing,Leadership,Creative Expression'),
        ),
        migrations.AlterField(
            model_name='entityregistration',
            name='eligibilty',
            field=models.TextField(default='Anyone can join a club or participate in extracurricular activities.'),
        ),
    ]
