# Generated by Django 5.1.3 on 2025-03-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0040_alter_entityregistration_about_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entrityrequest',
            name='unique_proposer_email_in_session',
        ),
    ]
