# Generated by Django 5.1.3 on 2025-03-17 09:21

import django.db.models.deletion
import intranetapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0041_remove_entrityrequest_unique_proposer_email_in_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='session_code',
            field=models.ForeignKey(default=intranetapp.models.get_current_session, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.currentsession'),
        ),
    ]
