# Generated by Django 5.1.3 on 2025-03-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0042_alter_user_table_session_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CUMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cu_logo', models.ImageField(blank=True, null=True, upload_to='entity_media/logos/perm/')),
            ],
        ),
    ]
