# Generated by Django 5.1.3 on 2025-04-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0043_cumedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('category', models.CharField(default='info', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('entity', models.ManyToManyField(blank=True, to='intranetapp.entity_type')),
                ('roles', models.ManyToManyField(blank=True, to='intranetapp.roles')),
            ],
        ),
    ]
