# Generated by Django 5.1.3 on 2025-04-19 09:19

import intranetapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0044_pushnotifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAndViews',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('News', 'News'), ('Views', 'Views')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_and_views/images/', validators=[intranetapp.models.validate_image_file_extension, intranetapp.models.validate_file_size])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
