# Generated by Django 5.1.3 on 2025-04-29 09:33

import django.db.models.deletion
import intranetapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0045_newsandviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRecordCeremony',
            fields=[
                ('rec_cer_id', models.AutoField(primary_key=True, serialize=False)),
                ('clusters', models.CharField(max_length=255)),
                ('departments', models.CharField(max_length=255)),
                ('entity_types', models.CharField(max_length=100)),
                ('entity_names', models.CharField(max_length=255)),
                ('level_of_activitys', models.CharField(max_length=100)),
                ('activity_types', models.CharField(max_length=255)),
                ('activity_event_names', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventPDFUpload',
            fields=[
                ('upload_id', models.AutoField(primary_key=True, serialize=False)),
                ('pdf_file', models.FileField(upload_to='event_pdfs/', validators=[intranetapp.models.validate_pdf_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_uploads', to='intranetapp.eventrecordceremony')),
            ],
        ),
    ]
