# Generated by Django 5.1.3 on 2025-05-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0046_eventrecordceremony_eventpdfupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpdfupload',
            name='insta_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpdfupload',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
