# Generated by Django 5.1.3 on 2025-05-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0047_eventpdfupload_insta_url_eventpdfupload_linkedin_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=255)),
                ('ratings_data', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
