# Generated by Django 5.1.3 on 2025-05-06 06:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0048_entityrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallRating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('registeration_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('ques_1', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ques_2', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ques_3', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ques_4', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ques_5', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ques_6', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ques_7', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ques_8', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ques_9', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ques_10', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('reg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranetapp.entityregistration')),
                ('session_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.currentsession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('reg_id', 'email'), name='unique_email_per_registration')],
            },
        ),
    ]
