# Generated by Django 5.1.3 on 2025-05-28 10:00

import django.db.models.deletion
import intranetapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0049_overallrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureEvent',
            fields=[
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=12)),
                ('feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('banner', models.ImageField(upload_to='feature_event/', validators=[intranetapp.models.validate_image_file_extension])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='sdg',
            fields=[
                ('sdg_id', models.AutoField(primary_key=True, serialize=False)),
                ('sdg_name', models.CharField(max_length=200)),
                ('status', models.CharField(default='active', max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='entrityrequest',
            old_name='entity_nature',
            new_name='entity_name',
        ),
        migrations.RemoveField(
            model_name='entrityrequest',
            name='faculty_adv_2_email',
        ),
        migrations.RemoveField(
            model_name='entrityrequest',
            name='faculty_adv_2_empcode',
        ),
        migrations.RemoveField(
            model_name='entrityrequest',
            name='faculty_adv_2_mobile',
        ),
        migrations.RemoveField(
            model_name='entrityrequest',
            name='faculty_adv_2_name',
        ),
        migrations.RemoveField(
            model_name='entrityrequest',
            name='faculty_coadv_2_email',
        ),
        migrations.RemoveField(
            model_name='entrityrequest',
            name='faculty_coadv_2_empcode',
        ),
        migrations.RemoveField(
            model_name='entrityrequest',
            name='faculty_coadv_2_mobile',
        ),
        migrations.RemoveField(
            model_name='entrityrequest',
            name='faculty_coadv_2_name',
        ),
        migrations.RemoveField(
            model_name='entrityrequest',
            name='proposed_name',
        ),
        migrations.RemoveField(
            model_name='entrityrequest',
            name='student_advsec_2_email',
        ),
        migrations.RemoveField(
            model_name='entrityrequest',
            name='student_advsec_2_mobile',
        ),
        migrations.RemoveField(
            model_name='entrityrequest',
            name='student_advsec_2_name',
        ),
        migrations.RemoveField(
            model_name='entrityrequest',
            name='student_advsec_2_uid',
        ),
        migrations.RemoveField(
            model_name='entrityrequest',
            name='student_sec_2_email',
        ),
        migrations.RemoveField(
            model_name='entrityrequest',
            name='student_sec_2_mobile',
        ),
        migrations.RemoveField(
            model_name='entrityrequest',
            name='student_sec_2_name',
        ),
        migrations.RemoveField(
            model_name='entrityrequest',
            name='student_sec_2_uid',
        ),
        migrations.AddField(
            model_name='entityregistration',
            name='Joint_Secretary_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jointsecretarydept', to='intranetapp.dept'),
        ),
        migrations.AddField(
            model_name='entityregistration',
            name='Secretary_dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='secretary_dept', to='intranetapp.dept'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entityregistration',
            name='faculty_advisory_dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_advisory_dept', to='intranetapp.dept'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entityregistration',
            name='faculty_co_advisory_dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_coadvisory', to='intranetapp.dept'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entityregistration',
            name='is_cordinator',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=12),
        ),
        migrations.AddField(
            model_name='entityregistration',
            name='mission',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entityregistration',
            name='objective',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entityregistration',
            name='session_code',
            field=models.ForeignKey(default=intranetapp.models.get_current_session, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.session'),
        ),
        migrations.AddField(
            model_name='entityregistration',
            name='vision',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entrityrequest',
            name='faculty_adv_1_dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_advisory', to='intranetapp.dept'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrityrequest',
            name='faculty_coadv_1_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_co_advisory', to='intranetapp.dept'),
        ),
        migrations.AddField(
            model_name='entrityrequest',
            name='is_cordinator',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=12),
        ),
        migrations.AddField(
            model_name='entrityrequest',
            name='mission',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='entrityrequest',
            name='objective',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='entrityrequest',
            name='student_advsec_1_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joint_secretary', to='intranetapp.dept'),
        ),
        migrations.AddField(
            model_name='entrityrequest',
            name='student_sec_1_dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='secretary', to='intranetapp.dept'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrityrequest',
            name='vision',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='budget_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='budget',
            name='session_code',
            field=models.ForeignKey(default=intranetapp.models.get_current_session, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.session'),
        ),
        migrations.AlterField(
            model_name='entrityrequest',
            name='faculty_coadv_1_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entrityrequest',
            name='faculty_coadv_1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entrityrequest',
            name='session_code',
            field=models.ForeignKey(default=intranetapp.models.get_current_session, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.session'),
        ),
        migrations.AlterField(
            model_name='entrityrequest',
            name='student_advsec_1_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entrityrequest',
            name='student_advsec_1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entrityrequest',
            name='student_advsec_1_uid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventjoinee',
            name='session_code',
            field=models.ForeignKey(default=intranetapp.models.get_current_session, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.session'),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='session_code',
            field=models.ForeignKey(default=intranetapp.models.get_current_session, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.session'),
        ),
        migrations.AlterField(
            model_name='membershipregistration',
            name='session_code',
            field=models.ForeignKey(default=intranetapp.models.get_current_session, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.session'),
        ),
        migrations.AlterField(
            model_name='membershipregistration',
            name='transaction_id',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='overallrating',
            name='session_code',
            field=models.ForeignKey(default=intranetapp.models.get_current_session, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.session'),
        ),
        migrations.AlterField(
            model_name='proposedcalender',
            name='session_code',
            field=models.ForeignKey(default=intranetapp.models.get_current_session, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.session'),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='session_code',
            field=models.ForeignKey(default=intranetapp.models.get_current_session, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.session'),
        ),
        migrations.AddField(
            model_name='entityregistration',
            name='sdg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.sdg'),
        ),
        migrations.AddField(
            model_name='entrityrequest',
            name='sdg',
            field=models.ManyToManyField(blank=True, null=True, to='intranetapp.sdg'),
        ),
    ]
