# Generated by Django 5.1.3 on 2025-05-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0050_featureevent_sdg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrityrequest',
            name='entity_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
