# Generated by Django 5.1.3 on 2025-05-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0051_alter_entrityrequest_entity_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityregistration',
            name='sdg',
        ),
        migrations.AddField(
            model_name='entityregistration',
            name='sdg',
            field=models.ManyToManyField(blank=True, null=True, to='intranetapp.sdg'),
        ),
    ]
