# Generated by Django 5.1.3 on 2025-06-03 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0052_remove_entityregistration_sdg_entityregistration_sdg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityregistration',
            name='sdg',
        ),
    ]
