# Generated by Django 5.1.3 on 2025-06-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0053_remove_entityregistration_sdg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrityrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'approved'), ('Interview Scheduled', 'interview Scheduled'), ('Rejected', 'Rejected'), ('Request Hold', 'Request Hold'), ('Registered', 'Registered')], default='Pending', max_length=100),
        ),
    ]
