# Generated by Django 5.1.3 on 2025-06-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0054_alter_entrityrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACTED',
            fields=[
                ('atd_id', models.AutoField(primary_key=True, serialize=False)),
                ('atd_name', models.CharField(blank=True, max_length=200, null=True)),
                ('atd_fullform', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NSQF',
            fields=[
                ('nsf_id', models.AutoField(primary_key=True, serialize=False)),
                ('nsf_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
