# Generated by Django 5.1.3 on 2025-06-06 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0055_acted_nsqf'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposedcalender',
            name='atd_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.acted'),
        ),
        migrations.AddField(
            model_name='proposedcalender',
            name='nsf_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.nsqf'),
        ),
        migrations.AddField(
            model_name='proposedcalender',
            name='part_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposedcalender',
            name='sdg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.sdg'),
        ),
    ]
