# Generated by Django 5.1.3 on 2025-06-06 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0056_proposedcalender_atd_id_proposedcalender_nsf_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityregistration',
            name='entcr_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranetapp.entrityrequest'),
        ),
    ]
