# Generated by Django 5.1.3 on 2025-06-06 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0057_entityregistration_entcr_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proposedcalender',
            unique_together={('reg_id', 'session_code', 'event_name', 'start_date', 'end_date')},
        ),
    ]
