# Generated by Django 5.1.3 on 2025-06-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0058_alter_proposedcalender_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequest',
            name='designation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
