# Generated by Django 5.1.3 on 2025-06-18 05:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0059_eventrequest_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='postevent',
            fields=[
                ('post_event_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_2_m', models.FileField(blank=True, null=True, upload_to='events_post/multiple_pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('circular', models.FileField(blank=True, null=True, upload_to='events_post/multiple_pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('document_pdf', models.FileField(blank=True, null=True, upload_to='events_post/document_pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('feedback_pdf', models.FileField(blank=True, null=True, upload_to='events_post/feedback_pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('attendance_sheet', models.FileField(blank=True, null=True, upload_to='events_post/attendance/', validators=[django.core.validators.FileExtensionValidator(['xlsx', 'xls', 'csv'])])),
                ('image_pdf', models.FileField(blank=True, null=True, upload_to='events_post/document_pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('er_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranetapp.eventrequest')),
                ('reg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranetapp.entityregistration')),
            ],
        ),
    ]
