# Generated by Django 5.1.3 on 2025-06-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0060_postevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposedcalender',
            name='other_skill',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposedcalender',
            name='selected_graduate_attributes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposedcalender',
            name='tech_skill',
            field=models.TextField(blank=True, null=True),
        ),
    ]
