# Generated by Django 6.0.6 on 2026-07-02 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0061_proposedcalender_other_skill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposedcalender',
            name='selected_graduate_attributes',
        ),
    ]
