# Generated by Django 6.0.6 on 2026-07-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0062_remove_proposedcalender_selected_graduate_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_code', models.TextField(blank=True, null=True)),
                ('registration_name', models.TextField(blank=True, null=True)),
                ('faculty_champion', models.TextField(blank=True, null=True)),
                ('employee_id', models.TextField(blank=True, null=True)),
                ('contact_number', models.TextField(blank=True, null=True)),
                ('email_id', models.TextField(blank=True, null=True)),
                ('cluster_department', models.TextField(blank=True, null=True)),
                ('secretary', models.TextField(blank=True, null=True)),
                ('sec_uid', models.TextField(blank=True, null=True)),
                ('secretary_email', models.TextField(blank=True, null=True)),
                ('secretary_contact', models.TextField(blank=True, null=True)),
                ('jt_secretary', models.TextField(blank=True, null=True)),
                ('jt_sec_uid', models.TextField(blank=True, null=True)),
                ('jt_sec_email', models.TextField(blank=True, null=True)),
                ('jt_sec_contact', models.TextField(blank=True, null=True)),
                ('login_id', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('approved_budget', models.FloatField(blank=True, null=True)),
                ('spent_budget', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Clubs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Communities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_id', models.TextField(blank=True, null=True)),
                ('name', models.TextField()),
                ('login_id', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('approved_budget', models.FloatField(blank=True, null=True)),
                ('spent_budget', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'communities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('login_id', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('dept_id', models.TextField(blank=True, null=True)),
                ('approved_budget', models.FloatField(blank=True, null=True)),
                ('spent_budget', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'departments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LegacyRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('login_id', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('role', models.TextField()),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProfessionalSocieties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_soc_id', models.TextField(blank=True, null=True)),
                ('name', models.TextField(unique=True)),
                ('login_id', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('approved_budget', models.FloatField(blank=True, null=True)),
                ('spent_budget', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'professional_societies',
                'managed': True,
            },
        ),
    ]
