# Generated by Django 6.0.6 on 2026-07-02 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranetapp', '0063_clubs_communities_departments_legacyroles_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clubs',
            table='clubs',
        ),
    ]
